### PR TITLE
fix: issues found with analyzer

### PR DESCRIPTION
**Pull request by summeroff**
fix few issues found with static code analyzer and some places what have catch by looking at code. 

some optimizations: with adding std::move() and changing functions params to references from values. Analyzer found more places where it can be applicable but it is relatively trivial fix and can be done later by separate PR when we need speedup code. 

Changes like this: 
`if ((buf.size() - noffset) < sizeof(int64_t)) {`
`if (buf.size() < noffset + sizeof(uint32_t)) {`
Here if 'noffset' somehow become bigger than buf.size() then subtractions result be some huge number as both values is unsigned size_t.

`uq += "_";` moved out of `if (parameters.size() > 0) {` as two functions can create conflicting ids. 
`test(int ) -> test_I4`
`test_I4()  -> test_I4`

### CODE REVIEW

**Review by EddyGharbi — APPROVED** [review]
Looks good to me 👍

**Comment by EddyGharbi** [comment]
Could you fix the merge conflicts?

**Comment by summeroff** [comment]
merged

**Comment by summeroff** [comment]
merged

**Pull request merged**
